name: NeuralShop

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0

    container_name: elasticsearch

    restart: always

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    networks:
      - neural_net

volumes:
  elasticsearch_data:

networks:
  neural_net:
    driver: bridge